# Generated by Django 4.1.7 on 2023-03-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('polls', '0003_rename_questions_question'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer_History',
            new_name='AnswerHistory',
        ),
    ]
