# Generated by Django 4.1.7 on 2023-03-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_answer_history_answerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='lvl',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
