# Generated by Django 4.1.7 on 2023-03-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.experience'),
        ),
    ]
