# Generated by Django 4.1.7 on 2023-03-27 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 19, 19, 40, 152254, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
