# Generated by Django 4.1.7 on 2023-03-29 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 16, 9, 35, 550878, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
